inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'db/migrate/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'doc/*'
    - 'Gemfile'
    - 'lib/tasks/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'db/schema.rb'

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
