# frozen_string_literal: true

encryption = Rails.application.config.active_record.encryption
encryption.primary_key = ApplicationConfig.active_record_encryption_primary_key
encryption.deterministic_key = ApplicationConfig.active_record_encryption_deterministic_key
encryption.key_derivation_salt = ApplicationConfig.active_record_encryption_key_derivation_salt
